ALTER ROLE mydb WITH PASSWORD 'aminul';
GRANT ALL PRIVILEGES ON DATABASE umsdb TO mydb;
GRANT CREATE ON SCHEMA public TO mydb;
GRANT ALL ON SCHEMA public TO mydb;
create table test(a varchar(100));

GRANT USAGE ON SCHEMA public TO mydb;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mydb;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO mydb;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO mydb;


