import express from 'express';
import { DesignationSetupController } from '../controller/setup/designation/designationSetupController';
import { designationValidator } from '../validation/designationValidation';
const router = express.Router();
const designationSetupController = new DesignationSetupController();
router.get('/', designationSetupController.getAll);
router.post('/', designationValidator(), designationSetupController.create);
router.patch('/:id', designationValidator(), designationSetupController.update);
router.delete('/',designationSetupController.deleteDepartment);
export default router;
