import express from 'express';
import { PoliceStationSetupController } from '../controller/setup/policeStation/policeStationSetupController';
import { policeStationCreateValidation, policeStationUpdateValidation } from '../validation/policeStationValidation';
const router = express.Router();
const policeStationSetupController = new PoliceStationSetupController();
router.get('/', policeStationSetupController.getAll);
router.post('/', policeStationCreateValidation(), policeStationSetupController.create);
router.patch('/:id', policeStationUpdateValidation(), policeStationSetupController.update);
router.delete('/',policeStationSetupController.deletePoliceStation);
export default router;
